[versions]
kotlin = "1.5.31"
agp = "7.0.2"
# formula: 23 + agp version
androidTools = "30.0.2"
okhttp = "4.9.0"
retrofit = "2.9.0"
androidX = "1.3.0"
espresso = "3.4.0"
coroutines = "1.3.8"
androidXTest = "1.4.0"
detekt = "1.18.0"
buildTools = "30.0.3"
compileSdk = "30"
targetSdk = "30"
minSdk = "21"
junit5 = "5.8.0"
junit5Platform = "1.8.0"
hamcrest = "2.2"

[libraries]
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinXCli = "org.jetbrains.kotlinx:kotlinx-cli:0.2.1"
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinStdlibJdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinCompilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlinHtml = "org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.3"
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinPoet = "com.squareup:kotlinpoet:1.7.2"

rxJava = "io.reactivex:rxjava:1.3.8"
commonsText = "org.apache.commons:commons-text:1.6"
commonsIo = "commons-io:commons-io:2.7"
commonsLang = "org.apache.commons:commons-lang3:3.8.1"
commonsConfiguration = "commons-configuration:commons-configuration:1.10"

okio = "com.squareup.okio:okio:2.7.0"
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttpMockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitConverterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofitConverterScalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

gson = "com.google.code.gson:gson:2.8.5"
kotson = "com.github.salomonbrys.kotson:kotson:2.5.0"
kotlinxSerialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1"

androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
layoutLibApi = { module = "com.android.tools.layoutlib:layoutlib-api", version.ref = "androidTools" }
androidSdkCommon = { module = "com.android.tools:sdk-common", version.ref = "androidTools" }
androidToolsCommon = { module = "com.android.tools:common", version.ref = "androidTools" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidX" }
material = { module = "com.google.android.material:material", version.ref = "androidX" }
recyclerView = "androidx.recyclerview:recyclerview:1.1.0"
swipeRefreshLayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidAnnotations = "androidx.annotation:annotation:1.1.0"
playServicesBase = "com.google.android.gms:play-services-base:17.0.0"

officialKubernetesClient = "io.kubernetes:client-java:8.0.0"
kubernetesClient = "io.fabric8:kubernetes-client:4.9.0"
kubernetesDsl = "com.fkorotkov:kubernetes-dsl:2.7.1"

ddmlib = "com.android.tools.ddms:ddmlib:26.2.0"
uiAutomator = "androidx.test.uiautomator:uiautomator:2.2.0"
testOrchestrator = { module = "androidx.test:orchestrator", version.ref = "androidXTest" }
androidXTestCore = { module = "androidx.test:core", version.ref = "androidXTest" }
androidXTestRunner = { module = "androidx.test:runner", version.ref = "androidXTest" }
androidXTestRules = { module = "androidx.test:rules", version.ref = "androidXTest" }
androidXTestExtJunit = "androidx.test.ext:junit:1.1.3"
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espressoWeb = { module = "androidx.test.espresso:espresso-web", version.ref = "espresso" }
espressoIntents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
espressoDescendantActions = "com.forkingcode.espresso.contrib:espresso-descendant-actions:1.4.0"
radiography = "com.squareup.radiography:radiography:2.4.1"
rx3Ilder = "com.squareup.rx.idler:rx3-idler:0.11.0"
r8 = "com.android.tools:r8:2.2.41"
proguardRetrace = "net.sf.proguard:proguard-retrace:6.2.2"
dexlib = "org.smali:dexlib2:2.3"

junit = "junit:junit:4.13"
truth = "com.google.truth:truth:1.0"
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
hamcrestLibrary = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
jsonPathAssert = "com.jayway.jsonpath:json-path-assert:2.4.0"
kotlinCompileTesting = "com.github.tschuchortdev:kotlin-compile-testing:1.4.0"
mockitoKotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"
mockitoJUnitJupiter = "org.mockito:mockito-junit-jupiter:3.3.3"
freeReflection = "com.github.tiann:FreeReflection:3.1.0"
antPattern = "io.github.azagniotov:ant-style-path-matcher:1.0.0"
okhttpMock = "com.github.gmazzo:okhttp-mock:1.4.0"
kotlinTest = "io.kotlintest:kotlintest:2.0.7"
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
nebulaIntegTest = "com.netflix.nebula:nebula-project-plugin:9.1.1"
testRetryGradle = "org.gradle:test-retry-gradle-plugin:1.3.1"
versionsGradle = "com.github.ben-manes:gradle-versions-plugin:0.39.0"
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junitVintageEngine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
junitPlatformRunner = { module = "org.junit.platform:junit-platform-runner", version.ref = "junit5Platform" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit5Platform" }

statsd = "com.timgroup:java-statsd-client:3.1.0"
slf4jApi = "org.slf4j:slf4j-api:1.7.28"
slackClient = "com.github.seratch:jslack-api-client:3.4.2"
teamcityClient = "org.jetbrains.teamcity:teamcity-rest-client:1.6.2"
googlePublish = "com.google.apis:google-api-services-androidpublisher:v3-rev86-1.25.0"
googleAuthLibrary = "com.google.auth:google-auth-library-oauth2-http:0.10.0"
jdgraphtCore = "org.jgrapht:jgrapht-core:1.5.1"

detektGradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# https://github.com/robolectric/robolectric/releases
robolectric = "org.robolectric:robolectric:4.7.1"

[bundles]
hamcrest = ["hamcrest", "hamcrestLibrary"]
